name: Deploy

on:
  push:
    branches:
      - global-linecount-code-status

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.13'

      - name: Install dependencies (client)
        run: cd pennant-ui/client && npm ci

      - name: Build client
        run: cd pennant-ui/client && NODE_OPTIONS='--max-old-space-size=4096' npm run build

      - name: Install dependencies (server)
        run: cd pennant-ui/server && npm ci

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            rm -rf /pennant-ui/client/dist
            rm -rf /pennant-ui/server/dist
            cp -r /pennant-ui/client/dist /pennant-ui/server/dist
            pm2 restart 13
